security:
    role_hierarchy:
      ROLE_SUPER_ADMIN: [ROLE_ADMIN]

      access_decision_manager:
        strategy: unanimous

    encoders:
      AppBundle\Entity\Admin:
          algorithm: bcrypt

    providers:
        db_provider:
            entity:
              class: AppBundle:Admin

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
              login_path: security_login
              check_path: security_login
              default_target_path: /
            logout:
              path: security_logout
              target: /

    access_control:
      - {path: /superadmin, roles: ROLE_SUPER_ADMIN}
      - {path: /attributes, roles: ROLE_SUPER_ADMIN}
      - {path: /book, roles: ROLE_ADMIN}